/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.lavacar;

import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Eragon Geb
 */
public class MenuFuncionario extends javax.swing.JFrame {
    private Company c;
    private MenuPrincipal menuP;
    
    public MenuFuncionario(Company c, MenuPrincipal m) {
        initComponents();
        this.c = c;
        menuP = m;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabFuncionário = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        cadVeiculo = new javax.swing.JPanel();
        ownerLabel = new javax.swing.JLabel();
        owner = new javax.swing.JTextField();
        concluirVeículo = new javax.swing.JButton();
        cancelarVeículo = new javax.swing.JButton();
        PanelVehicle4 = new javax.swing.JPanel();
        vehicleLabel2 = new javax.swing.JLabel();
        brandLabel2 = new javax.swing.JLabel();
        brand2 = new javax.swing.JTextField();
        boardLabel2 = new javax.swing.JLabel();
        board2 = new javax.swing.JTextField();
        modelLabel2 = new javax.swing.JLabel();
        model2 = new javax.swing.JTextField();
        yearLabel2 = new javax.swing.JLabel();
        year2 = new javax.swing.JTextField();
        descriptionLabel2 = new javax.swing.JLabel();
        description2 = new javax.swing.JTextField();
        sizeLabel2 = new javax.swing.JLabel();
        pequeno2 = new javax.swing.JRadioButton();
        medio2 = new javax.swing.JRadioButton();
        grande2 = new javax.swing.JRadioButton();
        cadCliente = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        rgLabel = new javax.swing.JLabel();
        rg = new javax.swing.JTextField();
        birthLabel = new javax.swing.JLabel();
        cpfLabel = new javax.swing.JLabel();
        cpf = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        phone1Label = new javax.swing.JLabel();
        phone1 = new javax.swing.JTextField();
        phone2Label = new javax.swing.JLabel();
        phone2 = new javax.swing.JTextField();
        concluirPessoa = new javax.swing.JButton();
        limparPessoa = new javax.swing.JButton();
        cadVeiculo2 = new javax.swing.JPanel();
        vehicleLabel = new javax.swing.JLabel();
        brandLabel = new javax.swing.JLabel();
        brand = new javax.swing.JTextField();
        boardLabel = new javax.swing.JLabel();
        board = new javax.swing.JTextField();
        modelLabel = new javax.swing.JLabel();
        model = new javax.swing.JTextField();
        yearLabel = new javax.swing.JLabel();
        year = new javax.swing.JTextField();
        descriptionLabel = new javax.swing.JLabel();
        description = new javax.swing.JTextField();
        sizeLabel = new javax.swing.JLabel();
        pequeno = new javax.swing.JRadioButton();
        medio = new javax.swing.JRadioButton();
        grande = new javax.swing.JRadioButton();
        colorLabel = new javax.swing.JLabel();
        color = new javax.swing.JTextField();
        birth = new javax.swing.JFormattedTextField();
        jCheckEditar = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabFuncionário.addTab("Serviço", jTabbedPane2);

        ownerLabel.setText("Proprietário: ");

        owner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownerActionPerformed(evt);
            }
        });

        concluirVeículo.setText("Concluir");
        concluirVeículo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concluirVeículoActionPerformed(evt);
            }
        });

        cancelarVeículo.setText("Cancelar");

        vehicleLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        vehicleLabel2.setText("Informações do veículo");

        brandLabel2.setText("Marca: ");

        brand2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brand2ActionPerformed(evt);
            }
        });

        boardLabel2.setText("Placa: ");

        board2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                board2ActionPerformed(evt);
            }
        });

        modelLabel2.setText("Modelo: ");

        model2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                model2ActionPerformed(evt);
            }
        });

        yearLabel2.setText("Ano: ");

        year2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                year2ActionPerformed(evt);
            }
        });

        descriptionLabel2.setText("Descrição: ");

        sizeLabel2.setText("Tamanho: ");

        buttonGroup1.add(pequeno2);
        pequeno2.setText("Pequeno");

        buttonGroup1.add(medio2);
        medio2.setText("Médio");
        medio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medio2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(grande2);
        grande2.setText("Grande");

        javax.swing.GroupLayout PanelVehicle4Layout = new javax.swing.GroupLayout(PanelVehicle4);
        PanelVehicle4.setLayout(PanelVehicle4Layout);
        PanelVehicle4Layout.setHorizontalGroup(
            PanelVehicle4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
            .addGroup(PanelVehicle4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelVehicle4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(PanelVehicle4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelVehicle4Layout.createSequentialGroup()
                            .addGroup(PanelVehicle4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelVehicle4Layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(descriptionLabel2)
                                    .addGap(165, 165, 165))
                                .addGroup(PanelVehicle4Layout.createSequentialGroup()
                                    .addGroup(PanelVehicle4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(PanelVehicle4Layout.createSequentialGroup()
                                            .addComponent(modelLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                            .addGap(1, 1, 1)
                                            .addComponent(model2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(PanelVehicle4Layout.createSequentialGroup()
                                            .addComponent(brandLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(brand2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(61, 61, 61)
                                    .addGroup(PanelVehicle4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(boardLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(yearLabel2, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addGap(23, 23, 23)
                            .addGroup(PanelVehicle4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(board2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(year2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(PanelVehicle4Layout.createSequentialGroup()
                            .addGroup(PanelVehicle4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelVehicle4Layout.createSequentialGroup()
                                    .addGap(25, 25, 25)
                                    .addComponent(sizeLabel2)
                                    .addGap(6, 6, 6)
                                    .addComponent(pequeno2)
                                    .addGap(18, 18, 18)
                                    .addComponent(medio2)
                                    .addGap(18, 18, 18)
                                    .addComponent(grande2))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelVehicle4Layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(description2, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(PanelVehicle4Layout.createSequentialGroup()
                            .addGap(118, 118, 118)
                            .addComponent(vehicleLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap()))
        );
        PanelVehicle4Layout.setVerticalGroup(
            PanelVehicle4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
            .addGroup(PanelVehicle4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelVehicle4Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vehicleLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(PanelVehicle4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelVehicle4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(brand2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(brandLabel2))
                        .addComponent(board2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(PanelVehicle4Layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(boardLabel2)))
                    .addGroup(PanelVehicle4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelVehicle4Layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addGroup(PanelVehicle4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(modelLabel2)
                                .addComponent(model2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(PanelVehicle4Layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addGroup(PanelVehicle4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(yearLabel2)
                                .addComponent(year2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(11, 11, 11)
                    .addComponent(descriptionLabel2)
                    .addGap(6, 6, 6)
                    .addComponent(description2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(PanelVehicle4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelVehicle4Layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(sizeLabel2))
                        .addComponent(pequeno2)
                        .addComponent(medio2)
                        .addComponent(grande2))
                    .addContainerGap()))
        );

        javax.swing.GroupLayout cadVeiculoLayout = new javax.swing.GroupLayout(cadVeiculo);
        cadVeiculo.setLayout(cadVeiculoLayout);
        cadVeiculoLayout.setHorizontalGroup(
            cadVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadVeiculoLayout.createSequentialGroup()
                .addGroup(cadVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cadVeiculoLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(concluirVeículo)
                        .addGap(18, 18, 18)
                        .addComponent(cancelarVeículo))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cadVeiculoLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(ownerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(owner, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(116, 116, 116))
            .addGroup(cadVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(cadVeiculoLayout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addComponent(PanelVehicle4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(90, Short.MAX_VALUE)))
        );
        cadVeiculoLayout.setVerticalGroup(
            cadVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadVeiculoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(cadVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ownerLabel)
                    .addComponent(owner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(323, 323, 323)
                .addGroup(cadVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(concluirVeículo)
                    .addComponent(cancelarVeículo))
                .addContainerGap(144, Short.MAX_VALUE))
            .addGroup(cadVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(cadVeiculoLayout.createSequentialGroup()
                    .addGap(79, 79, 79)
                    .addComponent(PanelVehicle4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(197, Short.MAX_VALUE)))
        );

        jTabFuncionário.addTab("Veículo", cadVeiculo);

        nameLabel.setText("Nome: ");

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        rgLabel.setText("RG: ");

        rg.setEditable(false);
        rg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rgActionPerformed(evt);
            }
        });

        birthLabel.setText("Data de Nascimento: ");

        cpfLabel.setText("CPF: ");

        cpf.setEditable(false);
        cpf.setColumns(9);
        cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfActionPerformed(evt);
            }
        });

        addressLabel.setText("Endereço: ");

        address.setEditable(false);
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });

        phone1Label.setText("Telefone:");

        phone1.setEditable(false);
        phone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone1ActionPerformed(evt);
            }
        });

        phone2Label.setText("Celular: ");

        phone2.setEditable(false);
        phone2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone2ActionPerformed(evt);
            }
        });

        concluirPessoa.setText("Concluir");
        concluirPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concluirPessoaActionPerformed(evt);
            }
        });

        limparPessoa.setText("Limpar");
        limparPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparPessoaActionPerformed(evt);
            }
        });

        vehicleLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        vehicleLabel.setText("Informações do veículo");

        brandLabel.setText("Marca: ");

        brand.setEditable(false);
        brand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandActionPerformed(evt);
            }
        });

        boardLabel.setText("Placa: ");

        board.setEditable(false);
        board.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boardActionPerformed(evt);
            }
        });

        modelLabel.setText("Modelo: ");

        model.setEditable(false);
        model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelActionPerformed(evt);
            }
        });

        yearLabel.setText("Ano: ");

        year.setEditable(false);
        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });

        descriptionLabel.setText("Descrição: ");

        description.setEditable(false);
        description.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionActionPerformed(evt);
            }
        });

        sizeLabel.setText("Tamanho: ");

        buttonGroup1.add(pequeno);
        pequeno.setText("Pequeno");
        pequeno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pequenoActionPerformed(evt);
            }
        });

        buttonGroup1.add(medio);
        medio.setText("Médio");
        medio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medioActionPerformed(evt);
            }
        });

        buttonGroup1.add(grande);
        grande.setText("Grande");
        grande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grandeActionPerformed(evt);
            }
        });

        colorLabel.setText("Cor: ");

        color.setEditable(false);
        color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cadVeiculo2Layout = new javax.swing.GroupLayout(cadVeiculo2);
        cadVeiculo2.setLayout(cadVeiculo2Layout);
        cadVeiculo2Layout.setHorizontalGroup(
            cadVeiculo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadVeiculo2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(cadVeiculo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadVeiculo2Layout.createSequentialGroup()
                        .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(52, Short.MAX_VALUE))
                    .addGroup(cadVeiculo2Layout.createSequentialGroup()
                        .addGroup(cadVeiculo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(modelLabel)
                            .addComponent(descriptionLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(colorLabel)
                        .addGap(27, 27, 27)
                        .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
            .addGroup(cadVeiculo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(cadVeiculo2Layout.createSequentialGroup()
                    .addGap(128, 128, 128)
                    .addComponent(vehicleLabel)
                    .addGap(118, 118, 118))
                .addGroup(cadVeiculo2Layout.createSequentialGroup()
                    .addGroup(cadVeiculo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(cadVeiculo2Layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(sizeLabel)
                            .addGap(6, 6, 6)
                            .addComponent(pequeno)
                            .addGap(18, 18, 18)
                            .addComponent(medio)
                            .addGap(18, 18, 18)
                            .addComponent(grande)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(cadVeiculo2Layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(cadVeiculo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(model, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(cadVeiculo2Layout.createSequentialGroup()
                                    .addComponent(brandLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(brand, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(61, 61, 61)
                            .addGroup(cadVeiculo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(boardLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(yearLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(23, 23, 23)
                            .addGroup(cadVeiculo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(board, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap()))
        );
        cadVeiculo2Layout.setVerticalGroup(
            cadVeiculo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadVeiculo2Layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addComponent(modelLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cadVeiculo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descriptionLabel)
                    .addComponent(colorLabel)
                    .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(cadVeiculo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadVeiculo2Layout.createSequentialGroup()
                    .addContainerGap(52, Short.MAX_VALUE)
                    .addComponent(vehicleLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(cadVeiculo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(cadVeiculo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(brand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(brandLabel))
                        .addComponent(board, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(cadVeiculo2Layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(boardLabel)))
                    .addGroup(cadVeiculo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(cadVeiculo2Layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(cadVeiculo2Layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addGroup(cadVeiculo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(yearLabel)
                                .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(123, 123, 123)
                    .addGroup(cadVeiculo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(cadVeiculo2Layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(sizeLabel))
                        .addComponent(pequeno)
                        .addComponent(medio)
                        .addComponent(grande))
                    .addContainerGap()))
        );

        birth.setEditable(false);
        birth.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        birth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthActionPerformed(evt);
            }
        });

        jCheckEditar.setText("jCheckBox1");
        jCheckEditar.setEnabled(false);

        javax.swing.GroupLayout cadClienteLayout = new javax.swing.GroupLayout(cadCliente);
        cadCliente.setLayout(cadClienteLayout);
        cadClienteLayout.setHorizontalGroup(
            cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadClienteLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadClienteLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(concluirPessoa)
                        .addGap(36, 36, 36)
                        .addComponent(limparPessoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckEditar)
                        .addGap(30, 30, 30))
                    .addGroup(cadClienteLayout.createSequentialGroup()
                        .addGroup(cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cadClienteLayout.createSequentialGroup()
                                    .addGroup(cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(cadClienteLayout.createSequentialGroup()
                                            .addComponent(nameLabel)
                                            .addGap(16, 16, 16)
                                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(21, 21, 21)
                                            .addComponent(rgLabel))
                                        .addGroup(cadClienteLayout.createSequentialGroup()
                                            .addComponent(birthLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(birth, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(cpfLabel)))
                                    .addGap(10, 10, 10)
                                    .addGroup(cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cadClienteLayout.createSequentialGroup()
                                    .addGroup(cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(phone1Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(cadClienteLayout.createSequentialGroup()
                                            .addComponent(phone1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(phone2Label)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(phone2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(cadVeiculo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(56, Short.MAX_VALUE))))
        );
        cadClienteLayout.setVerticalGroup(
            cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadClienteLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nameLabel))
                    .addGroup(cadClienteLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(rgLabel))
                    .addGroup(cadClienteLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(birthLabel)
                        .addComponent(birth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cpfLabel)
                        .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadClienteLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(addressLabel))
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadClienteLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phone2Label)
                            .addComponent(phone1Label)))
                    .addGroup(cadClienteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(phone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cadVeiculo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(concluirPessoa)
                    .addComponent(limparPessoa)
                    .addComponent(jCheckEditar))
                .addGap(25, 25, 25))
        );

        jTabFuncionário.addTab("Cliente", cadCliente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabFuncionário)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabFuncionário)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void year2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_year2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_year2ActionPerformed

    private void medio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medio2ActionPerformed

    private void board2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_board2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_board2ActionPerformed

    private void model2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_model2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_model2ActionPerformed

    private void brand2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brand2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brand2ActionPerformed

    private void ownerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ownerActionPerformed

    private void concluirVeículoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concluirVeículoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_concluirVeículoActionPerformed

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearActionPerformed

    private void medioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medioActionPerformed
        concluirPessoaActionPerformed(evt);
    }//GEN-LAST:event_medioActionPerformed

    private void boardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boardActionPerformed
        concluirPessoaActionPerformed(evt);
    }//GEN-LAST:event_boardActionPerformed

    private void modelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelActionPerformed
        concluirPessoaActionPerformed(evt);
    }//GEN-LAST:event_modelActionPerformed

    private void brandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandActionPerformed
        concluirPessoaActionPerformed(evt);
    }//GEN-LAST:event_brandActionPerformed

    private void concluirPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concluirPessoaActionPerformed
        Customer p = c.procuraPessoa(evt.getSource().toString());
        
        if(address.getText().equals("") || phone1.getText().equals("")
           || phone2.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Digite todas as informações para continuar",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        if(jCheckEditar.isSelected()) //Editar
        {
            p.setAddress(address.getText());
            p.setPhone1(phone1.getText());
            p.setPhone2(phone2.getText());
        }
        else //Cadastrar
        {
            int size;
            if(pequeno.isSelected())
                size = 1;
            else if(medio.isSelected())
                size = 2;
            else //grande.isSelected())
                size = 3;
            
            c.criaPessoa(name.getText(), rg.getText(), cpf.getText(),
                    birth.getText(), address.getText(), phone1.getText(),
                    phone2.getText());
            p.adicionaVeiculo(brand.getText(), board.getText(), model.getText(),
                    year.getText(), description.getText(), color.getText(),
                    size);
        }
        limparPessoaActionPerformed(evt);
    }//GEN-LAST:event_concluirPessoaActionPerformed

    private void phone2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone2ActionPerformed
        concluirPessoaActionPerformed(evt);
    }//GEN-LAST:event_phone2ActionPerformed

    private void phone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone1ActionPerformed
        concluirPessoaActionPerformed(evt);
    }//GEN-LAST:event_phone1ActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        concluirPessoaActionPerformed(evt);
    }//GEN-LAST:event_addressActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        JOptionPane.showMessageDialog(null, name.getText(), "WEy", JOptionPane.INFORMATION_MESSAGE);
        
        Customer p = c.procuraPessoa(name.getText());
        name.setEditable(false);
        
        this.address.setEditable(true);
        this.phone1.setEditable(true);
        this.phone2.setEditable(true);
        if(p == null)
        {
            this.rg.setEditable(true);
            this.cpf.setEditable(true);
            this.birth.setEditable(true);
            this.brand.setEditable(true);
            this.board.setEditable(true);
            this.model.setEditable(true);
            this.year.setEditable(true);
            this.color.setEditable(true);
            this.description.setEditable(true);
        }
        else
        {
            this.jCheckEditar.doClick(); //Liga a flag "editar"
            
            this.rg.setText(p.rg);
            this.cpf.setText(p.cpf);
            this.address.setText(p.address);
            this.birth.setText(p.dateOfBirth);
            this.brand.setText(p.vehiclesOfCustomer.get(0).getBrand());
            this.board.setText(p.vehiclesOfCustomer.get(0).getBoard());
            this.model.setText(p.vehiclesOfCustomer.get(0).getModel());
            this.year.setText(p.vehiclesOfCustomer.get(0).getYear());
            this.color.setText(p.vehiclesOfCustomer.get(0).getColor());
            this.description.setText(p.vehiclesOfCustomer.get(0).getDescription());
        }
    }//GEN-LAST:event_nameActionPerformed

    private void descriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionActionPerformed

    private void birthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthActionPerformed
        concluirPessoaActionPerformed(evt);
    }//GEN-LAST:event_birthActionPerformed

    private void limparPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparPessoaActionPerformed
        this.name.setEditable(true);
        this.rg.setEditable(true);
        this.cpf.setEditable(true);
        this.birth.setEditable(true);
        this.address.setEditable(true);
        this.phone1.setEditable(true);
        this.phone2.setEditable(true);
        this.brand.setEditable(true);
        this.board.setEditable(true);
        this.model.setEditable(true);
        this.year.setEditable(true);
        this.color.setEditable(true);
        this.description.setEditable(true);
        
        this.name.setText("");
        this.rg.setText("");
        this.cpf.setText("");
        this.address.setText("");
        this.birth.setText("");
        this.phone1.setText("");
        this.phone2.setText("");
        this.brand.setText("");
        this.board.setText("");
        this.model.setText("");
        this.year.setText("");
        this.color.setText("");
        this.description.setText("");  
    }//GEN-LAST:event_limparPessoaActionPerformed

    private void rgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rgActionPerformed
        concluirPessoaActionPerformed(evt);
    }//GEN-LAST:event_rgActionPerformed

    private void cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfActionPerformed
        concluirPessoaActionPerformed(evt);
    }//GEN-LAST:event_cpfActionPerformed

    private void pequenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pequenoActionPerformed
        concluirPessoaActionPerformed(evt);
    }//GEN-LAST:event_pequenoActionPerformed

    private void grandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grandeActionPerformed
        concluirPessoaActionPerformed(evt);
    }//GEN-LAST:event_grandeActionPerformed

    private void colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorActionPerformed
        concluirPessoaActionPerformed(evt);
    }//GEN-LAST:event_colorActionPerformed
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelVehicle4;
    private javax.swing.JTextField address;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JFormattedTextField birth;
    private javax.swing.JLabel birthLabel;
    private javax.swing.JTextField board;
    private javax.swing.JTextField board2;
    private javax.swing.JLabel boardLabel;
    private javax.swing.JLabel boardLabel2;
    private javax.swing.JTextField brand;
    private javax.swing.JTextField brand2;
    private javax.swing.JLabel brandLabel;
    private javax.swing.JLabel brandLabel2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel cadCliente;
    private javax.swing.JPanel cadVeiculo;
    private javax.swing.JPanel cadVeiculo2;
    private javax.swing.JButton cancelarVeículo;
    private javax.swing.JTextField color;
    private javax.swing.JLabel colorLabel;
    private javax.swing.JButton concluirPessoa;
    private javax.swing.JButton concluirVeículo;
    private javax.swing.JTextField cpf;
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JTextField description;
    private javax.swing.JTextField description2;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JLabel descriptionLabel2;
    private javax.swing.JRadioButton grande;
    private javax.swing.JRadioButton grande2;
    private javax.swing.JCheckBox jCheckEditar;
    private javax.swing.JTabbedPane jTabFuncionário;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton limparPessoa;
    private javax.swing.JRadioButton medio;
    private javax.swing.JRadioButton medio2;
    private javax.swing.JTextField model;
    private javax.swing.JTextField model2;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JLabel modelLabel2;
    private javax.swing.JTextField name;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField owner;
    private javax.swing.JLabel ownerLabel;
    private javax.swing.JRadioButton pequeno;
    private javax.swing.JRadioButton pequeno2;
    private javax.swing.JTextField phone1;
    private javax.swing.JLabel phone1Label;
    private javax.swing.JTextField phone2;
    private javax.swing.JLabel phone2Label;
    private javax.swing.JTextField rg;
    private javax.swing.JLabel rgLabel;
    private javax.swing.JLabel sizeLabel;
    private javax.swing.JLabel sizeLabel2;
    private javax.swing.JLabel vehicleLabel;
    private javax.swing.JLabel vehicleLabel2;
    private javax.swing.JTextField year;
    private javax.swing.JTextField year2;
    private javax.swing.JLabel yearLabel;
    private javax.swing.JLabel yearLabel2;
    // End of variables declaration//GEN-END:variables

}
