/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.lavacar;

import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Eragon Geb
 */
public class MenuFuncionario extends javax.swing.JFrame {
    private Company c;
    private MenuPrincipal menuP;
    
    public MenuFuncionario(Company c, MenuPrincipal m) {
        initComponents();
        this.c = c;
        menuP = m;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        cards = new javax.swing.JPanel();
        menuF = new javax.swing.JPanel();
        botCadastrarCliente = new javax.swing.JButton();
        botCadastrarVeiculo = new javax.swing.JButton();
        botLavar = new javax.swing.JButton();
        botColocarNaFila = new javax.swing.JButton();
        botDiagnostico = new javax.swing.JButton();
        botEditar = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        cadCliente = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        phone1 = new javax.swing.JTextField();
        phone2 = new javax.swing.JTextField();
        rgLabel = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        cpfLabel = new javax.swing.JLabel();
        rg = new javax.swing.JTextField();
        birthLabel = new javax.swing.JLabel();
        cpf = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        dia = new javax.swing.JTextField();
        phone1Label = new javax.swing.JLabel();
        mes = new javax.swing.JTextField();
        phone2Label = new javax.swing.JLabel();
        ano = new javax.swing.JTextField();
        cancelarPessoa = new javax.swing.JButton();
        concluirPessoa = new javax.swing.JButton();
        PanelVehicle1 = new javax.swing.JPanel();
        sizeLabel1 = new javax.swing.JLabel();
        brandLabel1 = new javax.swing.JLabel();
        modelLabel1 = new javax.swing.JLabel();
        boardLabel1 = new javax.swing.JLabel();
        descriptionLabel1 = new javax.swing.JLabel();
        brand1 = new javax.swing.JTextField();
        model1 = new javax.swing.JTextField();
        pequeno1 = new javax.swing.JRadioButton();
        board1 = new javax.swing.JTextField();
        medio1 = new javax.swing.JRadioButton();
        year1 = new javax.swing.JTextField();
        grande1 = new javax.swing.JRadioButton();
        description1 = new javax.swing.JTextField();
        vehicleLabel1 = new javax.swing.JLabel();
        anoLabel2 = new javax.swing.JLabel();
        cadVeiculo = new javax.swing.JPanel();
        concluirVeículo = new javax.swing.JButton();
        cancelarVeículo = new javax.swing.JButton();
        ownerLabel = new javax.swing.JLabel();
        owner = new javax.swing.JTextField();
        PanelVehicle2 = new javax.swing.JPanel();
        sizeLabel2 = new javax.swing.JLabel();
        brandLabel2 = new javax.swing.JLabel();
        modelLabel2 = new javax.swing.JLabel();
        boardLabel2 = new javax.swing.JLabel();
        descriptionLabel2 = new javax.swing.JLabel();
        brand2 = new javax.swing.JTextField();
        model2 = new javax.swing.JTextField();
        pequeno2 = new javax.swing.JRadioButton();
        board2 = new javax.swing.JTextField();
        medio2 = new javax.swing.JRadioButton();
        year2 = new javax.swing.JTextField();
        grande2 = new javax.swing.JRadioButton();
        description2 = new javax.swing.JTextField();
        vehicleLabel2 = new javax.swing.JLabel();
        yearLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cards.setLayout(new java.awt.CardLayout());

        menuF.setMaximumSize(new java.awt.Dimension(440, 672));

        botCadastrarCliente.setText("Cadastrar cliente");
        botCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCadastrarClienteActionPerformed(evt);
            }
        });

        botCadastrarVeiculo.setText("Cadastrar veículo");
        botCadastrarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCadastrarVeiculoActionPerformed(evt);
            }
        });

        botLavar.setText("Lavar o próximo");

        botColocarNaFila.setText("Colocar na fila");

        botDiagnostico.setText("Diagnóstico do veículo");
        botDiagnostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botDiagnosticoActionPerformed(evt);
            }
        });

        botEditar.setText("Editar informações");

        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuFLayout = new javax.swing.GroupLayout(menuF);
        menuF.setLayout(menuFLayout);
        menuFLayout.setHorizontalGroup(
            menuFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuFLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(menuFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(botColocarNaFila, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botDiagnostico)
                    .addComponent(botEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botCadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botCadastrarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botLavar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voltar))
                .addGap(41, 41, 41))
        );

        menuFLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botCadastrarCliente, botCadastrarVeiculo, botColocarNaFila, botDiagnostico, botEditar, botLavar});

        menuFLayout.setVerticalGroup(
            menuFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuFLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(botCadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botCadastrarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botLavar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botColocarNaFila)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(voltar)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        menuFLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {botCadastrarCliente, botCadastrarVeiculo, botColocarNaFila, botDiagnostico, botEditar, botLavar});

        cards.add(menuF, "card1");

        nameLabel.setText("Nome: ");

        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });

        phone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone1ActionPerformed(evt);
            }
        });

        phone2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone2ActionPerformed(evt);
            }
        });

        rgLabel.setText("RG: ");

        cpfLabel.setText("CPF: ");

        birthLabel.setText("Data de Nascimento: ");

        cpf.setColumns(9);

        addressLabel.setText("Endereço: ");

        dia.setColumns(2);
        dia.setText("DD");
        dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaActionPerformed(evt);
            }
        });

        phone1Label.setText("Telefone:");

        mes.setColumns(2);
        mes.setText("MM");
        mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesActionPerformed(evt);
            }
        });

        phone2Label.setText("Celular: ");

        ano.setColumns(4);
        ano.setText("AAAA");

        cancelarPessoa.setText("Cancelar");
        cancelarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarPessoaActionPerformed(evt);
            }
        });

        concluirPessoa.setText("Concluir");
        concluirPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concluirPessoaActionPerformed(evt);
            }
        });

        sizeLabel1.setText("Tamanho: ");

        brandLabel1.setText("Marca: ");

        modelLabel1.setText("Modelo: ");

        boardLabel1.setText("Placa: ");

        descriptionLabel1.setText("Descrição: ");

        brand1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brand1ActionPerformed(evt);
            }
        });

        model1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                model1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(pequeno1);
        pequeno1.setText("Pequeno");

        board1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                board1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(medio1);
        medio1.setText("Médio");
        medio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medio1ActionPerformed(evt);
            }
        });

        year1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                year1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(grande1);
        grande1.setText("Grande");

        vehicleLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        vehicleLabel1.setText("Informações do veículo");

        anoLabel2.setText("Ano: ");

        javax.swing.GroupLayout PanelVehicle1Layout = new javax.swing.GroupLayout(PanelVehicle1);
        PanelVehicle1.setLayout(PanelVehicle1Layout);
        PanelVehicle1Layout.setHorizontalGroup(
            PanelVehicle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
            .addGroup(PanelVehicle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelVehicle1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(PanelVehicle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelVehicle1Layout.createSequentialGroup()
                            .addGroup(PanelVehicle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelVehicle1Layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(descriptionLabel1)
                                    .addGap(165, 165, 165))
                                .addGroup(PanelVehicle1Layout.createSequentialGroup()
                                    .addGroup(PanelVehicle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(PanelVehicle1Layout.createSequentialGroup()
                                            .addComponent(modelLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                            .addGap(1, 1, 1)
                                            .addComponent(model1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(PanelVehicle1Layout.createSequentialGroup()
                                            .addComponent(brandLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(brand1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(61, 61, 61)
                                    .addGroup(PanelVehicle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(boardLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(anoLabel2, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addGap(23, 23, 23)
                            .addGroup(PanelVehicle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(board1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(year1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(PanelVehicle1Layout.createSequentialGroup()
                            .addGroup(PanelVehicle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelVehicle1Layout.createSequentialGroup()
                                    .addGap(25, 25, 25)
                                    .addComponent(sizeLabel1)
                                    .addGap(6, 6, 6)
                                    .addComponent(pequeno1)
                                    .addGap(18, 18, 18)
                                    .addComponent(medio1)
                                    .addGap(18, 18, 18)
                                    .addComponent(grande1))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelVehicle1Layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(description1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(PanelVehicle1Layout.createSequentialGroup()
                            .addGap(118, 118, 118)
                            .addComponent(vehicleLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap()))
        );
        PanelVehicle1Layout.setVerticalGroup(
            PanelVehicle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
            .addGroup(PanelVehicle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelVehicle1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vehicleLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(PanelVehicle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelVehicle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(brand1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(brandLabel1))
                        .addComponent(board1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(PanelVehicle1Layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(boardLabel1)))
                    .addGroup(PanelVehicle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelVehicle1Layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addGroup(PanelVehicle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(modelLabel1)
                                .addComponent(model1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(PanelVehicle1Layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addGroup(PanelVehicle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(anoLabel2)
                                .addComponent(year1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(11, 11, 11)
                    .addComponent(descriptionLabel1)
                    .addGap(6, 6, 6)
                    .addComponent(description1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(PanelVehicle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelVehicle1Layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(sizeLabel1))
                        .addComponent(pequeno1)
                        .addComponent(medio1)
                        .addComponent(grande1))
                    .addContainerGap()))
        );

        javax.swing.GroupLayout cadClienteLayout = new javax.swing.GroupLayout(cadCliente);
        cadCliente.setLayout(cadClienteLayout);
        cadClienteLayout.setHorizontalGroup(
            cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadClienteLayout.createSequentialGroup()
                .addGroup(cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cadClienteLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(concluirPessoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelarPessoa)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(cadClienteLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cadClienteLayout.createSequentialGroup()
                                .addGroup(cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(cadClienteLayout.createSequentialGroup()
                                        .addComponent(nameLabel)
                                        .addGap(16, 16, 16)
                                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(21, 21, 21)
                                        .addComponent(rgLabel))
                                    .addGroup(cadClienteLayout.createSequentialGroup()
                                        .addComponent(birthLabel)
                                        .addGap(4, 4, 4)
                                        .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cpfLabel)))
                                .addGap(10, 10, 10)
                                .addGroup(cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cadClienteLayout.createSequentialGroup()
                                .addGroup(cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(phone1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(cadClienteLayout.createSequentialGroup()
                                        .addComponent(phone1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(phone2Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(phone2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(address))))))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(cadClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelVehicle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        cadClienteLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cpf, phone1, phone2, rg});

        cadClienteLayout.setVerticalGroup(
            cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadClienteLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nameLabel))
                    .addGroup(cadClienteLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(rgLabel))
                    .addGroup(cadClienteLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cadClienteLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(birthLabel)
                            .addGroup(cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cpfLabel)
                                .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(11, 11, 11)
                .addGroup(cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadClienteLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(addressLabel))
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadClienteLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phone2Label)
                            .addComponent(phone1Label)))
                    .addGroup(cadClienteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(phone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelVehicle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(concluirPessoa)
                    .addComponent(cancelarPessoa))
                .addGap(25, 25, 25))
        );

        cards.add(cadCliente, "card2");

        concluirVeículo.setText("Concluir");
        concluirVeículo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concluirVeículoActionPerformed(evt);
            }
        });

        cancelarVeículo.setText("Cancelar");

        ownerLabel.setText("Proprietário: ");

        owner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownerActionPerformed(evt);
            }
        });

        sizeLabel2.setText("Tamanho: ");

        brandLabel2.setText("Marca: ");

        modelLabel2.setText("Modelo: ");

        boardLabel2.setText("Placa: ");

        descriptionLabel2.setText("Descrição: ");

        brand2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brand2ActionPerformed(evt);
            }
        });

        model2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                model2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(pequeno2);
        pequeno2.setText("Pequeno");

        board2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                board2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(medio2);
        medio2.setText("Médio");
        medio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medio2ActionPerformed(evt);
            }
        });

        year2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                year2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(grande2);
        grande2.setText("Grande");

        vehicleLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        vehicleLabel2.setText("Informações do veículo");

        yearLabel2.setText("Ano: ");

        javax.swing.GroupLayout PanelVehicle2Layout = new javax.swing.GroupLayout(PanelVehicle2);
        PanelVehicle2.setLayout(PanelVehicle2Layout);
        PanelVehicle2Layout.setHorizontalGroup(
            PanelVehicle2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
            .addGroup(PanelVehicle2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelVehicle2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(PanelVehicle2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelVehicle2Layout.createSequentialGroup()
                            .addGroup(PanelVehicle2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelVehicle2Layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(descriptionLabel2)
                                    .addGap(165, 165, 165))
                                .addGroup(PanelVehicle2Layout.createSequentialGroup()
                                    .addGroup(PanelVehicle2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(PanelVehicle2Layout.createSequentialGroup()
                                            .addComponent(modelLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                            .addGap(1, 1, 1)
                                            .addComponent(model2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(PanelVehicle2Layout.createSequentialGroup()
                                            .addComponent(brandLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(brand2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(61, 61, 61)
                                    .addGroup(PanelVehicle2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(boardLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(yearLabel2, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addGap(23, 23, 23)
                            .addGroup(PanelVehicle2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(board2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(year2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(PanelVehicle2Layout.createSequentialGroup()
                            .addGroup(PanelVehicle2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelVehicle2Layout.createSequentialGroup()
                                    .addGap(25, 25, 25)
                                    .addComponent(sizeLabel2)
                                    .addGap(6, 6, 6)
                                    .addComponent(pequeno2)
                                    .addGap(18, 18, 18)
                                    .addComponent(medio2)
                                    .addGap(18, 18, 18)
                                    .addComponent(grande2))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelVehicle2Layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(description2, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(PanelVehicle2Layout.createSequentialGroup()
                            .addGap(118, 118, 118)
                            .addComponent(vehicleLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap()))
        );
        PanelVehicle2Layout.setVerticalGroup(
            PanelVehicle2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
            .addGroup(PanelVehicle2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelVehicle2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vehicleLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(PanelVehicle2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelVehicle2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(brand2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(brandLabel2))
                        .addComponent(board2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(PanelVehicle2Layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(boardLabel2)))
                    .addGroup(PanelVehicle2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelVehicle2Layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addGroup(PanelVehicle2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(modelLabel2)
                                .addComponent(model2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(PanelVehicle2Layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addGroup(PanelVehicle2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(yearLabel2)
                                .addComponent(year2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(11, 11, 11)
                    .addComponent(descriptionLabel2)
                    .addGap(6, 6, 6)
                    .addComponent(description2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(PanelVehicle2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelVehicle2Layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(sizeLabel2))
                        .addComponent(pequeno2)
                        .addComponent(medio2)
                        .addComponent(grande2))
                    .addContainerGap()))
        );

        javax.swing.GroupLayout cadVeiculoLayout = new javax.swing.GroupLayout(cadVeiculo);
        cadVeiculo.setLayout(cadVeiculoLayout);
        cadVeiculoLayout.setHorizontalGroup(
            cadVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadVeiculoLayout.createSequentialGroup()
                .addGroup(cadVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cadVeiculoLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(concluirVeículo)
                        .addGap(18, 18, 18)
                        .addComponent(cancelarVeículo))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cadVeiculoLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(ownerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(owner, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(116, 116, 116))
            .addGroup(cadVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(cadVeiculoLayout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addComponent(PanelVehicle2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(41, Short.MAX_VALUE)))
        );
        cadVeiculoLayout.setVerticalGroup(
            cadVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadVeiculoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(cadVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ownerLabel)
                    .addComponent(owner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(323, 323, 323)
                .addGroup(cadVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(concluirVeículo)
                    .addComponent(cancelarVeículo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(cadVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(cadVeiculoLayout.createSequentialGroup()
                    .addGap(79, 79, 79)
                    .addComponent(PanelVehicle2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(198, Short.MAX_VALUE)))
        );

        cards.add(cadVeiculo, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cards, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cards, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCadastrarClienteActionPerformed
        CardLayout cl = (CardLayout)cards.getLayout();
        this.setSize(500, 700);
        cl.show(cards, "card2");
        cards.setSize(460, 500);
    }//GEN-LAST:event_botCadastrarClienteActionPerformed

    private void botCadastrarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCadastrarVeiculoActionPerformed
        CardLayout cl = (CardLayout)cards.getLayout();
        cl.show(cards, "card3");
        cards.setSize(400, 350);
    }//GEN-LAST:event_botCadastrarVeiculoActionPerformed

    private void botDiagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botDiagnosticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botDiagnosticoActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        this.setVisible(false);
        menuP.setVisible(true);
    }//GEN-LAST:event_voltarActionPerformed
    
    private void concluirVeículoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concluirVeículoActionPerformed
        ArrayList clientes = (ArrayList<Customer>)c.getCustomers();
        Customer p = c.procuraPessoa(owner.getText());
        if(p == null)
        {
            JOptionPane.showMessageDialog(null, "Cliente não cadastrado!", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Veículo cadastrado com sucesso!", "Cadastro de veículo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
    }//GEN-LAST:event_concluirVeículoActionPerformed

    private void concluirPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concluirPessoaActionPerformed
        c.criaPessoa(name.getText(), rg.getText(), cpf.getText(),
            dia.getText(), mes.getText(), ano.getText(),
            address.getText(), phone1.getText(), phone2.getText());
    }//GEN-LAST:event_concluirPessoaActionPerformed
    
    private void mesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesActionPerformed

    private void diaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diaActionPerformed

    private void phone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phone1ActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void phone2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phone2ActionPerformed

    private void ownerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ownerActionPerformed

    private void brand1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brand1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brand1ActionPerformed

    private void model1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_model1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_model1ActionPerformed

    private void board1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_board1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_board1ActionPerformed

    private void medio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medio1ActionPerformed

    private void year1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_year1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_year1ActionPerformed

    private void brand2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brand2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brand2ActionPerformed

    private void model2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_model2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_model2ActionPerformed

    private void board2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_board2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_board2ActionPerformed

    private void medio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medio2ActionPerformed

    private void year2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_year2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_year2ActionPerformed

    private void cancelarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarPessoaActionPerformed
        CardLayout cl = (CardLayout)cards.getLayout();
        cl.show(cards, "card1");
        cards.setSize(300, 400);
    }//GEN-LAST:event_cancelarPessoaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelVehicle1;
    private javax.swing.JPanel PanelVehicle2;
    private javax.swing.JTextField address;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField ano;
    private javax.swing.JLabel anoLabel2;
    private javax.swing.JLabel birthLabel;
    private javax.swing.JTextField board1;
    private javax.swing.JTextField board2;
    private javax.swing.JLabel boardLabel1;
    private javax.swing.JLabel boardLabel2;
    private javax.swing.JButton botCadastrarCliente;
    private javax.swing.JButton botCadastrarVeiculo;
    private javax.swing.JButton botColocarNaFila;
    private javax.swing.JButton botDiagnostico;
    private javax.swing.JButton botEditar;
    private javax.swing.JButton botLavar;
    private javax.swing.JTextField brand1;
    private javax.swing.JTextField brand2;
    private javax.swing.JLabel brandLabel1;
    private javax.swing.JLabel brandLabel2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel cadCliente;
    private javax.swing.JPanel cadVeiculo;
    private javax.swing.JButton cancelarPessoa;
    private javax.swing.JButton cancelarVeículo;
    private javax.swing.JPanel cards;
    private javax.swing.JButton concluirPessoa;
    private javax.swing.JButton concluirVeículo;
    private javax.swing.JTextField cpf;
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JTextField description1;
    private javax.swing.JTextField description2;
    private javax.swing.JLabel descriptionLabel1;
    private javax.swing.JLabel descriptionLabel2;
    private javax.swing.JTextField dia;
    private javax.swing.JRadioButton grande1;
    private javax.swing.JRadioButton grande2;
    private javax.swing.JRadioButton medio1;
    private javax.swing.JRadioButton medio2;
    private javax.swing.JPanel menuF;
    private javax.swing.JTextField mes;
    private javax.swing.JTextField model1;
    private javax.swing.JTextField model2;
    private javax.swing.JLabel modelLabel1;
    private javax.swing.JLabel modelLabel2;
    private javax.swing.JTextField name;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField owner;
    private javax.swing.JLabel ownerLabel;
    private javax.swing.JRadioButton pequeno1;
    private javax.swing.JRadioButton pequeno2;
    private javax.swing.JTextField phone1;
    private javax.swing.JLabel phone1Label;
    private javax.swing.JTextField phone2;
    private javax.swing.JLabel phone2Label;
    private javax.swing.JTextField rg;
    private javax.swing.JLabel rgLabel;
    private javax.swing.JLabel sizeLabel1;
    private javax.swing.JLabel sizeLabel2;
    private javax.swing.JLabel vehicleLabel1;
    private javax.swing.JLabel vehicleLabel2;
    private javax.swing.JButton voltar;
    private javax.swing.JTextField year1;
    private javax.swing.JTextField year2;
    private javax.swing.JLabel yearLabel2;
    // End of variables declaration//GEN-END:variables

}
