/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lavacar;

import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

public class MenuFuncionario extends javax.swing.JFrame {
    private Company c;
    private MenuPrincipal menuP;
    private ArrayList<Vehicle> fila;
    Calendar cal = Calendar.getInstance();
    
    public MenuFuncionario(Company c, MenuPrincipal m, ArrayList<Vehicle> f) {
        initComponents();
        this.c = c;
        menuP = m;
        fila = f;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabFuncionário = new javax.swing.JTabbedPane();
        exeServico = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DefaultListModel listModel = new DefaultListModel();
        list = new javax.swing.JList<>();
        adicionarNaFila = new javax.swing.JButton();
        removerDaFila = new javax.swing.JButton();
        boardFila = new javax.swing.JTextField();
        boardLabelFila = new javax.swing.JLabel();
        lavarFila = new javax.swing.JButton();
        diagnostico = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        motor = new javax.swing.JTextField();
        oleo = new javax.swing.JTextField();
        tanque = new javax.swing.JTextField();
        pneus = new javax.swing.JTextField();
        combustivel = new javax.swing.JTextField();
        bateria = new javax.swing.JTextField();
        motorLabel = new javax.swing.JLabel();
        oleoLabel = new javax.swing.JLabel();
        tanqueLabel = new javax.swing.JLabel();
        combustivelLabel = new javax.swing.JLabel();
        pneusLabel = new javax.swing.JLabel();
        bateriaLabel = new javax.swing.JLabel();
        sugestoes = new javax.swing.JTextArea();
        sugestoesLabel = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        cadCliente = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        rgLabel = new javax.swing.JLabel();
        rg = new javax.swing.JTextField();
        birthLabel = new javax.swing.JLabel();
        cpfLabel = new javax.swing.JLabel();
        cpf = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        phone1Label = new javax.swing.JLabel();
        phone1 = new javax.swing.JTextField();
        phone2Label = new javax.swing.JLabel();
        phone2 = new javax.swing.JTextField();
        concluirPessoa = new javax.swing.JButton();
        cancelarPessoa = new javax.swing.JButton();
        cadVeiculo2 = new javax.swing.JPanel();
        vehicleLabel = new javax.swing.JLabel();
        brandLabel = new javax.swing.JLabel();
        brand = new javax.swing.JTextField();
        boardLabel = new javax.swing.JLabel();
        board = new javax.swing.JTextField();
        modelLabel = new javax.swing.JLabel();
        model = new javax.swing.JTextField();
        yearLabel = new javax.swing.JLabel();
        year = new javax.swing.JTextField();
        colorLabel = new javax.swing.JLabel();
        color = new javax.swing.JTextField();
        descriptionLabel = new javax.swing.JLabel();
        description = new javax.swing.JTextField();
        sizeLabel = new javax.swing.JLabel();
        pequeno = new javax.swing.JRadioButton();
        medio = new javax.swing.JRadioButton();
        grande = new javax.swing.JRadioButton();
        birth = new javax.swing.JFormattedTextField();
        jTextArea1 = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        cadVeiculo = new javax.swing.JPanel();
        ownerLabel = new javax.swing.JLabel();
        owner = new javax.swing.JTextField();
        concluirVeículo = new javax.swing.JButton();
        cancelarVeículo = new javax.swing.JButton();
        PanelVehicle4 = new javax.swing.JPanel();
        vehicleLabel2 = new javax.swing.JLabel();
        brandLabel2 = new javax.swing.JLabel();
        brand2 = new javax.swing.JTextField();
        boardLabel2 = new javax.swing.JLabel();
        board2 = new javax.swing.JTextField();
        modelLabel2 = new javax.swing.JLabel();
        model2 = new javax.swing.JTextField();
        yearLabel2 = new javax.swing.JLabel();
        year2 = new javax.swing.JTextField();
        descriptionLabel2 = new javax.swing.JLabel();
        description2 = new javax.swing.JTextField();
        sizeLabel2 = new javax.swing.JLabel();
        pequeno2 = new javax.swing.JRadioButton();
        medio2 = new javax.swing.JRadioButton();
        grande2 = new javax.swing.JRadioButton();
        color2 = new javax.swing.JTextField();
        colorLabel2 = new javax.swing.JLabel();
        jTextArea2 = new javax.swing.JTextArea();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTabFuncionário.setAutoscrolls(true);
        jTabFuncionário.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        list.setModel(listModel);
        jScrollPane1.setViewportView(list);

        adicionarNaFila.setText("Adicionar");
        adicionarNaFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarNaFilaActionPerformed(evt);
            }
        });

        removerDaFila.setText("Remover");
        removerDaFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerDaFilaActionPerformed(evt);
            }
        });

        boardLabelFila.setText("Placa: ");

        lavarFila.setText("Lavar o próximo");
        lavarFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lavarFilaActionPerformed(evt);
            }
        });

        diagnostico.setText("Diagnóstico do Veículo");
        diagnostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagnosticoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Fila atual");

        motor.setEditable(false);

        oleo.setEditable(false);

        tanque.setEditable(false);

        pneus.setEditable(false);

        combustivel.setEditable(false);

        bateria.setEditable(false);

        motorLabel.setText("Motor: ");

        oleoLabel.setText("Óleo: ");

        tanqueLabel.setText("Tanque: ");

        combustivelLabel.setText("Combustível: ");

        pneusLabel.setText("Pneus: ");

        bateriaLabel.setText("Bateria: ");

        sugestoes.setEditable(false);
        sugestoes.setColumns(20);
        sugestoes.setRows(5);

        sugestoesLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sugestoesLabel.setText("Sugestões de serviços futuros");

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout exeServicoLayout = new javax.swing.GroupLayout(exeServico);
        exeServico.setLayout(exeServicoLayout);
        exeServicoLayout.setHorizontalGroup(
            exeServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exeServicoLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(exeServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(exeServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exeServicoLayout.createSequentialGroup()
                            .addComponent(boardLabelFila)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(boardFila, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(exeServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(adicionarNaFila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(removerDaFila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(exeServicoLayout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(lavarFila, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exeServicoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(80, 80, 80)))
                .addGap(30, 30, 30)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(exeServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exeServicoLayout.createSequentialGroup()
                        .addGroup(exeServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(combustivelLabel)
                            .addComponent(tanqueLabel)
                            .addComponent(oleoLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(exeServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(exeServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(oleo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                .addComponent(tanque, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(combustivel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(diagnostico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sugestoesLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sugestoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exeServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(exeServicoLayout.createSequentialGroup()
                            .addComponent(motorLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(motor, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(exeServicoLayout.createSequentialGroup()
                            .addComponent(pneusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pneus)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exeServicoLayout.createSequentialGroup()
                        .addComponent(bateriaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bateria, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(70, 70, 70))
        );

        exeServicoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bateria, combustivel, motor, oleo, pneus, tanque});

        exeServicoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {adicionarNaFila, removerDaFila});

        exeServicoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {diagnostico, lavarFila});

        exeServicoLayout.setVerticalGroup(
            exeServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exeServicoLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(exeServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lavarFila))
                .addGroup(exeServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(exeServicoLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(exeServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(motor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(motorLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(exeServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pneus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pneusLabel))
                        .addGap(8, 8, 8)
                        .addGroup(exeServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(oleoLabel)
                            .addComponent(oleo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(exeServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tanque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tanqueLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(exeServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combustivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combustivelLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(exeServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bateriaLabel))
                        .addGap(18, 18, 18)
                        .addComponent(sugestoesLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sugestoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(exeServicoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(exeServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(exeServicoLayout.createSequentialGroup()
                                .addComponent(adicionarNaFila)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removerDaFila))
                            .addGroup(exeServicoLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(exeServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(boardFila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(boardLabelFila))))))
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(exeServicoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jSeparator6)
                .addContainerGap())
        );

        exeServicoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {combustivel, motor, oleo, pneus, tanque});

        exeServicoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {adicionarNaFila, removerDaFila});

        exeServicoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {diagnostico, lavarFila});

        jTabFuncionário.addTab("Serviço", exeServico);

        cadCliente.setForeground(new java.awt.Color(100, 200, 200));

        nameLabel.setText("Nome: ");

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        rgLabel.setText("RG: ");

        rg.setEditable(false);
        rg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rgActionPerformed(evt);
            }
        });

        birthLabel.setText("Data de Nascimento: ");

        cpfLabel.setText("CPF: ");

        cpf.setEditable(false);
        cpf.setColumns(9);
        cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfActionPerformed(evt);
            }
        });

        addressLabel.setText("Endereço: ");

        address.setEditable(false);
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });

        phone1Label.setText("Telefone:");

        phone1.setEditable(false);
        phone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone1ActionPerformed(evt);
            }
        });

        phone2Label.setText("Celular: ");

        phone2.setEditable(false);
        phone2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone2ActionPerformed(evt);
            }
        });

        concluirPessoa.setText("Concluir");
        concluirPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concluirPessoaActionPerformed(evt);
            }
        });

        cancelarPessoa.setText("Cancelar");
        cancelarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarPessoaActionPerformed(evt);
            }
        });

        vehicleLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        vehicleLabel.setText("Informações do veículo");

        brandLabel.setText("Marca: ");

        brand.setEditable(false);
        brand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandActionPerformed(evt);
            }
        });

        boardLabel.setText("Placa: ");

        board.setEditable(false);
        board.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boardActionPerformed(evt);
            }
        });

        modelLabel.setText("Modelo: ");

        model.setEditable(false);
        model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelActionPerformed(evt);
            }
        });

        yearLabel.setText("Ano: ");

        year.setEditable(false);
        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });

        colorLabel.setText("Cor: ");

        color.setEditable(false);
        color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorActionPerformed(evt);
            }
        });

        descriptionLabel.setText("Descrição: ");

        description.setEditable(false);
        description.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionActionPerformed(evt);
            }
        });

        sizeLabel.setText("Tamanho: ");

        buttonGroup1.add(pequeno);
        pequeno.setText("Pequeno");

        buttonGroup1.add(medio);
        medio.setText("Médio");

        buttonGroup1.add(grande);
        grande.setText("Grande");

        javax.swing.GroupLayout cadVeiculo2Layout = new javax.swing.GroupLayout(cadVeiculo2);
        cadVeiculo2.setLayout(cadVeiculo2Layout);
        cadVeiculo2Layout.setHorizontalGroup(
            cadVeiculo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadVeiculo2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(cadVeiculo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadVeiculo2Layout.createSequentialGroup()
                        .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(52, Short.MAX_VALUE))
                    .addGroup(cadVeiculo2Layout.createSequentialGroup()
                        .addGroup(cadVeiculo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(descriptionLabel)
                            .addComponent(modelLabel)
                            .addComponent(brandLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(colorLabel)
                        .addGap(27, 27, 27)
                        .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
            .addGroup(cadVeiculo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(cadVeiculo2Layout.createSequentialGroup()
                    .addGap(128, 128, 128)
                    .addComponent(vehicleLabel)
                    .addGap(118, 118, 118))
                .addGroup(cadVeiculo2Layout.createSequentialGroup()
                    .addGroup(cadVeiculo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(cadVeiculo2Layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(sizeLabel)
                            .addGap(6, 6, 6)
                            .addComponent(pequeno)
                            .addGap(18, 18, 18)
                            .addComponent(medio)
                            .addGap(18, 18, 18)
                            .addComponent(grande)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(cadVeiculo2Layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(cadVeiculo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(model, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(brand, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(61, 61, 61)
                            .addGroup(cadVeiculo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(boardLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(yearLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(23, 23, 23)
                            .addGroup(cadVeiculo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(board, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap()))
        );
        cadVeiculo2Layout.setVerticalGroup(
            cadVeiculo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadVeiculo2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(brandLabel)
                .addGap(18, 18, 18)
                .addComponent(modelLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cadVeiculo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descriptionLabel)
                    .addComponent(colorLabel)
                    .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(cadVeiculo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadVeiculo2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vehicleLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(cadVeiculo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(brand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(board, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(cadVeiculo2Layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(boardLabel)))
                    .addGroup(cadVeiculo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(cadVeiculo2Layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(cadVeiculo2Layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addGroup(cadVeiculo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(yearLabel)
                                .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(123, 123, 123)
                    .addGroup(cadVeiculo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(cadVeiculo2Layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(sizeLabel))
                        .addComponent(pequeno)
                        .addComponent(medio)
                        .addComponent(grande))
                    .addContainerGap()))
        );

        birth.setEditable(false);
        birth.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        birth.setText("31/12/1950");
        birth.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        birth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(2);
        jTextArea1.setText("Cadastro -> Digite um nome não cadastrado no sistema\nEditar dados -> Digite o nome de um cliente já existente");

        javax.swing.GroupLayout cadClienteLayout = new javax.swing.GroupLayout(cadCliente);
        cadCliente.setLayout(cadClienteLayout);
        cadClienteLayout.setHorizontalGroup(
            cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadClienteLayout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addGroup(cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadClienteLayout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addGap(16, 16, 16)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(rgLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadVeiculo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cadClienteLayout.createSequentialGroup()
                            .addComponent(birthLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(birth, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cpfLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cadClienteLayout.createSequentialGroup()
                            .addGroup(cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(phone1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(cadClienteLayout.createSequentialGroup()
                                    .addComponent(phone1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(phone2Label)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(phone2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(cadClienteLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(concluirPessoa)
                        .addGap(47, 47, 47)
                        .addComponent(cancelarPessoa)))
                .addGap(106, 106, 106))
            .addGroup(cadClienteLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                    .addGroup(cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                        .addComponent(jSeparator2)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        cadClienteLayout.setVerticalGroup(
            cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadClienteLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rgLabel)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(birthLabel)
                    .addComponent(birth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpfLabel)
                    .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(addressLabel)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(phone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phone1Label)
                    .addComponent(phone2Label)
                    .addComponent(phone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cadVeiculo2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(cadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelarPessoa)
                    .addComponent(concluirPessoa))
                .addContainerGap())
        );

        jTabFuncionário.addTab("Cliente", cadCliente);

        cadVeiculo.setForeground(new java.awt.Color(100, 200, 200));

        ownerLabel.setText("Proprietário: ");

        owner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownerActionPerformed(evt);
            }
        });

        concluirVeículo.setText("Concluir");
        concluirVeículo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concluirVeículoActionPerformed(evt);
            }
        });

        cancelarVeículo.setText("Cancelar");
        cancelarVeículo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarVeículoActionPerformed(evt);
            }
        });

        vehicleLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        vehicleLabel2.setText("Informações do veículo");

        brandLabel2.setText("Marca: ");

        brand2.setEditable(false);
        brand2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brand2ActionPerformed(evt);
            }
        });

        boardLabel2.setText("Placa: ");

        board2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                board2ActionPerformed(evt);
            }
        });

        modelLabel2.setText("Modelo: ");

        model2.setEditable(false);
        model2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                model2ActionPerformed(evt);
            }
        });

        yearLabel2.setText("Ano: ");

        year2.setEditable(false);
        year2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                year2ActionPerformed(evt);
            }
        });

        descriptionLabel2.setText("Descrição: ");

        description2.setEditable(false);
        description2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                description2ActionPerformed(evt);
            }
        });

        sizeLabel2.setText("Tamanho: ");

        buttonGroup1.add(pequeno2);
        pequeno2.setSelected(true);
        pequeno2.setText("Pequeno");

        buttonGroup1.add(medio2);
        medio2.setText("Médio");

        buttonGroup1.add(grande2);
        grande2.setText("Grande");

        color2.setEditable(false);
        color2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color2ActionPerformed(evt);
            }
        });

        colorLabel2.setText("Cor: ");

        javax.swing.GroupLayout PanelVehicle4Layout = new javax.swing.GroupLayout(PanelVehicle4);
        PanelVehicle4.setLayout(PanelVehicle4Layout);
        PanelVehicle4Layout.setHorizontalGroup(
            PanelVehicle4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelVehicle4Layout.createSequentialGroup()
                .addContainerGap(255, Short.MAX_VALUE)
                .addComponent(colorLabel2)
                .addGap(27, 27, 27)
                .addComponent(color2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(PanelVehicle4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(modelLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelVehicle4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelVehicle4Layout.createSequentialGroup()
                    .addGap(128, 128, 128)
                    .addComponent(vehicleLabel2)
                    .addGap(118, 118, Short.MAX_VALUE))
                .addGroup(PanelVehicle4Layout.createSequentialGroup()
                    .addGroup(PanelVehicle4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelVehicle4Layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(sizeLabel2)
                            .addGap(6, 6, 6)
                            .addComponent(pequeno2)
                            .addGap(18, 18, 18)
                            .addComponent(medio2)
                            .addGap(18, 18, 18)
                            .addComponent(grande2)
                            .addGap(0, 37, Short.MAX_VALUE))
                        .addGroup(PanelVehicle4Layout.createSequentialGroup()
                            .addGroup(PanelVehicle4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(PanelVehicle4Layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(descriptionLabel2)
                                    .addGap(188, 188, 188))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelVehicle4Layout.createSequentialGroup()
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(PanelVehicle4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(model2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(PanelVehicle4Layout.createSequentialGroup()
                                            .addComponent(brandLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(brand2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(61, 61, 61)
                                    .addGroup(PanelVehicle4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(boardLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(yearLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(23, 23, 23)))
                            .addGroup(PanelVehicle4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(board2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(year2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelVehicle4Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(description2, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        PanelVehicle4Layout.setVerticalGroup(
            PanelVehicle4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVehicle4Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(modelLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelVehicle4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colorLabel2)
                    .addComponent(color2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(128, Short.MAX_VALUE))
            .addGroup(PanelVehicle4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelVehicle4Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vehicleLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(PanelVehicle4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelVehicle4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(brand2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(brandLabel2))
                        .addComponent(board2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(PanelVehicle4Layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(boardLabel2)))
                    .addGroup(PanelVehicle4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelVehicle4Layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(model2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PanelVehicle4Layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addGroup(PanelVehicle4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(yearLabel2)
                                .addComponent(year2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(11, 11, 11)
                    .addComponent(descriptionLabel2)
                    .addGap(6, 6, 6)
                    .addComponent(description2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(PanelVehicle4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelVehicle4Layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(sizeLabel2))
                        .addComponent(pequeno2)
                        .addComponent(medio2)
                        .addComponent(grande2))
                    .addContainerGap()))
        );

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(2);
        jTextArea2.setText("Cadastro -> Digite uma placa não cadastrada no sistema\nEditar dados -> Digite um nome e placa já existentes");

        javax.swing.GroupLayout cadVeiculoLayout = new javax.swing.GroupLayout(cadVeiculo);
        cadVeiculo.setLayout(cadVeiculoLayout);
        cadVeiculoLayout.setHorizontalGroup(
            cadVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadVeiculoLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(cadVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cadVeiculoLayout.createSequentialGroup()
                        .addComponent(ownerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(owner, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                    .addComponent(jSeparator5)
                    .addGroup(cadVeiculoLayout.createSequentialGroup()
                        .addComponent(concluirVeículo)
                        .addGap(43, 43, 43)
                        .addComponent(cancelarVeículo))
                    .addComponent(PanelVehicle4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );
        cadVeiculoLayout.setVerticalGroup(
            cadVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadVeiculoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jTextArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(cadVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ownerLabel)
                    .addComponent(owner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelVehicle4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(concluirVeículo)
                    .addComponent(cancelarVeículo))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabFuncionário.addTab("Veículo", cadVeiculo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabFuncionário)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabFuncionário)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void year2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_year2ActionPerformed
        concluirVeículoActionPerformed(evt);
    }//GEN-LAST:event_year2ActionPerformed

    private void board2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_board2ActionPerformed
        if(owner.getText().equals("") || board2.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Digite todas as informações para "
                    + "continuar", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Customer p = c.procuraPessoa(owner.getText());
        if(p == null)
        {
            JOptionPane.showMessageDialog(null, "Cliente não cadastrado! Use a aba "
                    + "'cliente' para efetuar o cadastro antes de adicionar ou editar "
                    + "um veículo!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Vehicle v = c.procuraVeiculo(board2.getText());
        owner.setEditable(false);
        board2.setEditable(false);
        
        if(v == null) //Cadastrar
        {          
            /* Permite ao usuário inserir informações em
            todos os campos */
            this.brand2.setEditable(true);
            this.board2.setEditable(true);
            this.model2.setEditable(true);
            this.year2.setEditable(true);
            this.color2.setEditable(true);
            this.description2.setEditable(true);
        }
        else //Editar
        {
            /* Imprime as informações guardadas no sistema
            Permitindo editar apenas alguns campos */
            this.brand2.setText(v.getBrand());
            this.board2.setText(v.getBoard());
            this.model2.setText(v.getModel());
            this.year2.setText(v.getYear());
            this.color2.setText(v.getColor());
            this.description2.setText(v.getDescription());
            int size = v.getSize();
            if(size == 1)
                pequeno2.doClick();
            else if(size==2)
                medio2.doClick();
            else //size == 3
                grande2.doClick();

            this.color2.setEditable(true);
            this.description2.setEditable(true);
        }


    }//GEN-LAST:event_board2ActionPerformed

    private void model2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_model2ActionPerformed
        concluirVeículoActionPerformed(evt);
    }//GEN-LAST:event_model2ActionPerformed

    private void brand2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brand2ActionPerformed
        concluirVeículoActionPerformed(evt);
    }//GEN-LAST:event_brand2ActionPerformed

    private void ownerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownerActionPerformed
        board2ActionPerformed(evt);
    }//GEN-LAST:event_ownerActionPerformed

    private void concluirVeículoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concluirVeículoActionPerformed
        Customer p = c.procuraPessoa(owner.getText());
        Vehicle v = c.procuraVeiculo(board2.getText());
        if(v == null) //Cadastrar
        {
            int size;
            if(pequeno2.isSelected())
                size = 1;
            else if(medio2.isSelected())
                size = 2;
            else //grande.isSelected())
                size = 3;
            
            p.adicionaVeiculo(brand2.getText(), board2.getText(), model2.getText(),
                    year2.getText(), color2.getText(), description2.getText(), size);
        }
        else //Editar
        {
            v.setColor(color2.getText());
            v.setDescription(description2.getText());
        }
        cancelarVeículoActionPerformed(evt);
    }//GEN-LAST:event_concluirVeículoActionPerformed

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
        concluirPessoaActionPerformed(evt);
    }//GEN-LAST:event_yearActionPerformed

    private void boardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boardActionPerformed
        concluirPessoaActionPerformed(evt);
    }//GEN-LAST:event_boardActionPerformed

    private void modelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelActionPerformed
        concluirPessoaActionPerformed(evt);
    }//GEN-LAST:event_modelActionPerformed

    private void brandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandActionPerformed
        concluirPessoaActionPerformed(evt);
    }//GEN-LAST:event_brandActionPerformed

    private void concluirPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concluirPessoaActionPerformed
        Customer p = c.procuraPessoa(name.getText());
        
        //Checa se todas as informações foram digitadas
        if(address.getText().equals("") || phone1.getText().equals("")
           || phone2.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Digite todas as informações para continuar",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(p == null) //Cadastrar
        {
            int size;
            if(pequeno.isSelected())
                size = 1;
            else if(medio.isSelected())
                size = 2;
            else //grande.isSelected())
                size = 3;
            
            p = c.criaPessoa(name.getText(), rg.getText(), cpf.getText(),
                    birth.getText(), address.getText(), phone1.getText(),
                    phone2.getText());
            p.adicionaVeiculo(brand.getText(), board.getText(), model.getText(),
                    year.getText(), color.getText(), description.getText(),
                    size);
        }
        else //Editar
        {
            p.setAddress(address.getText());
            p.setPhone1(phone1.getText());
            p.setPhone2(phone2.getText());
        }
        cancelarPessoaActionPerformed(evt);
    }//GEN-LAST:event_concluirPessoaActionPerformed

    private void phone2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone2ActionPerformed
        concluirPessoaActionPerformed(evt);
    }//GEN-LAST:event_phone2ActionPerformed

    private void phone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone1ActionPerformed
        concluirPessoaActionPerformed(evt);
    }//GEN-LAST:event_phone1ActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        concluirPessoaActionPerformed(evt);
    }//GEN-LAST:event_addressActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        Customer p = c.procuraPessoa(name.getText());
        name.setEditable(false);

        if(p == null) //Cadastrar
        {
            /* Permite ao usuário inserir informações em
            todos os campos */
            this.rg.setEditable(true);
            this.cpf.setEditable(true);
            this.birth.setEditable(true);
            this.address.setEditable(true);
            this.phone1.setEditable(true);
            this.phone2.setEditable(true);

            this.brand.setEditable(true);
            this.board.setEditable(true);
            this.model.setEditable(true);
            this.year.setEditable(true);
            this.color.setEditable(true);
            this.description.setEditable(true);
        }
        else //Editar
        {
            /* Imprime as informações guardadas no sistema
            Permitindo editar apenas alguns campos */
            this.rg.setText(p.getRg());
            this.cpf.setText(p.getCpf());
            this.address.setText(p.getAddress());
            this.birth.setText(p.getDateOfBirth());
            this.phone1.setText(p.getPhone1());
            this.phone2.setText(p.getPhone2());
            this.brand.setText(p.getVehiclesOfCustomer().get(0).getBrand());
            this.board.setText(p.getVehiclesOfCustomer().get(0).getBoard());
            this.model.setText(p.getVehiclesOfCustomer().get(0).getModel());
            this.year.setText(p.getVehiclesOfCustomer().get(0).getYear());
            this.color.setText(p.getVehiclesOfCustomer().get(0).getColor());
            this.description.setText(p.getVehiclesOfCustomer().get(0).getDescription());
            int size = p.getVehiclesOfCustomer().get(0).getSize();
            if(size == 1)
                pequeno.doClick();
            else if(size==2)
                medio.doClick();
            else //size == 3
                grande.doClick();
            
            this.address.setEditable(true);
            this.phone1.setEditable(true);
            this.phone2.setEditable(true);
        }
    }//GEN-LAST:event_nameActionPerformed

    private void descriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionActionPerformed
        concluirPessoaActionPerformed(evt);
    }//GEN-LAST:event_descriptionActionPerformed

    private void birthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthActionPerformed
        concluirPessoaActionPerformed(evt);
    }//GEN-LAST:event_birthActionPerformed

    private void cancelarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarPessoaActionPerformed
        this.name.setEditable(true);
        this.rg.setEditable(false);
        this.cpf.setEditable(false);
        this.birth.setEditable(false);
        this.address.setEditable(false);
        this.phone1.setEditable(false);
        this.phone2.setEditable(false);
        this.brand.setEditable(false);
        this.board.setEditable(false);
        this.model.setEditable(false);
        this.year.setEditable(false);
        this.color.setEditable(false);
        this.description.setEditable(false);
        
        this.name.setText("");
        this.rg.setText("");
        this.cpf.setText("");
        this.address.setText("");
        this.birth.setText("31/12/1950");
        this.phone1.setText("");
        this.phone2.setText("");
        this.brand.setText("");
        this.board.setText("");
        this.model.setText("");
        this.year.setText("");
        this.color.setText("");
        this.description.setText("");  
    }//GEN-LAST:event_cancelarPessoaActionPerformed

    private void rgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rgActionPerformed
        concluirPessoaActionPerformed(evt);
    }//GEN-LAST:event_rgActionPerformed

    private void cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfActionPerformed
        concluirPessoaActionPerformed(evt);
    }//GEN-LAST:event_cpfActionPerformed

    private void colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorActionPerformed
        concluirPessoaActionPerformed(evt);
    }//GEN-LAST:event_colorActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        c.encerrar();
    }//GEN-LAST:event_formWindowClosing

    private void description2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_description2ActionPerformed
        concluirVeículoActionPerformed(evt);
    }//GEN-LAST:event_description2ActionPerformed

    private void color2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color2ActionPerformed
        concluirVeículoActionPerformed(evt);
    }//GEN-LAST:event_color2ActionPerformed

    private void cancelarVeículoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarVeículoActionPerformed
        this.owner.setEditable(true);
        this.board2.setEditable(true);
        this.brand2.setEditable(false);
        this.model2.setEditable(false);
        this.year2.setEditable(false);
        this.color2.setEditable(false);
        this.description2.setEditable(false);
        
        this.brand2.setText("");
        this.board2.setText("");
        this.model2.setText("");
        this.year2.setText("");
        this.color2.setText("");
        this.description2.setText("");  
    }//GEN-LAST:event_cancelarVeículoActionPerformed

    private void adicionarNaFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarNaFilaActionPerformed
        
        Vehicle v = c.procuraVeiculo(boardFila.getText());
        if(v == null) //Não está cadastrado no sistema
        {
            JOptionPane.showMessageDialog(null, "Veículo não cadastrado!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else //Tudo ok
        {
            /* Adiciona no sistema, na interface e atualiza */
            c.getService().getFila().add(v);
            listModel.add(0, boardFila.getText());
            list.setModel(listModel);
        }
    }//GEN-LAST:event_adicionarNaFilaActionPerformed

    private void removerDaFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerDaFilaActionPerformed
        //Se não tem nenhum item selecionado
        if(list.getSelectedIndex() == -1)
            JOptionPane.showMessageDialog(null, "Posição inválida. Selecione um item"
                    + " para remover da lista", "Error", JOptionPane.ERROR_MESSAGE);
        else //Se tem algum selecionado
        {
            c.getService().getFila().remove(list.getSelectedIndex());
            listModel.remove(list.getSelectedIndex());
        }
    }//GEN-LAST:event_removerDaFilaActionPerformed

    private void lavarFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lavarFilaActionPerformed
        //Se a lista está vazia
        if(list.getModel().getSize() == 0)
            JOptionPane.showMessageDialog(null, "Adicione veículos na fila para"
                    + "lavá-los!", "Error", JOptionPane.ERROR_MESSAGE);
        else //Se tem veículos na fila
            c.getService().executar();
        //tem que remover do sistema e da interface
    }//GEN-LAST:event_lavarFilaActionPerformed

    private void diagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagnosticoActionPerformed
        //Se não tem nenhum item selecionado
        if(list.getSelectedIndex() == -1)
            JOptionPane.showMessageDialog(null, "Posição inválida. Selecione um veículo"
                    + " para fazer o diagnóstico", "Error", JOptionPane.ERROR_MESSAGE);
        else //Se tem algum selecionado
        {
            
            sugestoes.setText("");
            
            String placa = listModel.get(list.getSelectedIndex());
            Vehicle v = c.procuraVeiculo(placa);
            
            if(c.verificarMotor(v) == true)
                motor.setText("OK");
            else
            {
                motor.setText("FALHA NO MOTOR");
                sugestoes.setText(sugestoes.getText() + "Arrumar o motor\n");
            }
            if(c.verificarPneus(v) == true)
                pneus.setText("OK");
            else
            {
                pneus.setText("GASTOS");
                sugestoes.setText(sugestoes.getText() + "Trocar pneus\n");
            }
            if(c.verificarOleo(v) == true)
                oleo.setText("OK");
            else
            {
                oleo.setText("VAZANDO");
                sugestoes.setText(sugestoes.getText() + "Fixar o vazamento de óleo\n");
            }
            if(c.verificarTanque(v) == true)
                tanque.setText("CHEIO");
            else
                tanque.setText("COMB. ACABANDO");
            if(c.verificarCombustivel(v) == true)
                combustivel.setText("OK");
            else
            {
                combustivel.setText("VAZANDO");
                sugestoes.setText(sugestoes.getText() + "Fixar o vazamento de combustível\n");
            }
            if(c.verificarBateria(v) == true)
                bateria.setText("OK");
            else
            {
                bateria.setText("COM PROBLEMA");
                sugestoes.setText(sugestoes.getText() + "Arrumar a bateria\n");
            }
            if(c.verificarPolimento(v) == false)
                sugestoes.setText(sugestoes.getText() + "Polimento\n");
            if(c.verificarPintura(v) == false)
                sugestoes.setText(sugestoes.getText() + "Pintura\n");
            
            /* Muda os atributos. Seria o mesmo que consertar
            todos os problemas e fazer com que na próxima visita
            apareçam outros */
            v.randomizeState();
        }
    }//GEN-LAST:event_diagnosticoActionPerformed
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelVehicle4;
    private javax.swing.JTextField address;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JButton adicionarNaFila;
    private javax.swing.JTextField bateria;
    private javax.swing.JLabel bateriaLabel;
    private javax.swing.JFormattedTextField birth;
    private javax.swing.JLabel birthLabel;
    private javax.swing.JTextField board;
    private javax.swing.JTextField board2;
    private javax.swing.JTextField boardFila;
    private javax.swing.JLabel boardLabel;
    private javax.swing.JLabel boardLabel2;
    private javax.swing.JLabel boardLabelFila;
    private javax.swing.JTextField brand;
    private javax.swing.JTextField brand2;
    private javax.swing.JLabel brandLabel;
    private javax.swing.JLabel brandLabel2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel cadCliente;
    private javax.swing.JPanel cadVeiculo;
    private javax.swing.JPanel cadVeiculo2;
    private javax.swing.JButton cancelarPessoa;
    private javax.swing.JButton cancelarVeículo;
    private javax.swing.JTextField color;
    private javax.swing.JTextField color2;
    private javax.swing.JLabel colorLabel;
    private javax.swing.JLabel colorLabel2;
    private javax.swing.JTextField combustivel;
    private javax.swing.JLabel combustivelLabel;
    private javax.swing.JButton concluirPessoa;
    private javax.swing.JButton concluirVeículo;
    private javax.swing.JTextField cpf;
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JTextField description;
    private javax.swing.JTextField description2;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JLabel descriptionLabel2;
    private javax.swing.JButton diagnostico;
    private javax.swing.JPanel exeServico;
    private javax.swing.JRadioButton grande;
    private javax.swing.JRadioButton grande2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTabbedPane jTabFuncionário;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JButton lavarFila;
    private javax.swing.JList<String> list;
    private javax.swing.JRadioButton medio;
    private javax.swing.JRadioButton medio2;
    private javax.swing.JTextField model;
    private javax.swing.JTextField model2;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JLabel modelLabel2;
    private javax.swing.JTextField motor;
    private javax.swing.JLabel motorLabel;
    private javax.swing.JTextField name;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField oleo;
    private javax.swing.JLabel oleoLabel;
    private javax.swing.JTextField owner;
    private javax.swing.JLabel ownerLabel;
    private javax.swing.JRadioButton pequeno;
    private javax.swing.JRadioButton pequeno2;
    private javax.swing.JTextField phone1;
    private javax.swing.JLabel phone1Label;
    private javax.swing.JTextField phone2;
    private javax.swing.JLabel phone2Label;
    private javax.swing.JTextField pneus;
    private javax.swing.JLabel pneusLabel;
    private javax.swing.JButton removerDaFila;
    private javax.swing.JTextField rg;
    private javax.swing.JLabel rgLabel;
    private javax.swing.JLabel sizeLabel;
    private javax.swing.JLabel sizeLabel2;
    private javax.swing.JTextArea sugestoes;
    private javax.swing.JLabel sugestoesLabel;
    private javax.swing.JTextField tanque;
    private javax.swing.JLabel tanqueLabel;
    private javax.swing.JLabel vehicleLabel;
    private javax.swing.JLabel vehicleLabel2;
    private javax.swing.JTextField year;
    private javax.swing.JTextField year2;
    private javax.swing.JLabel yearLabel;
    private javax.swing.JLabel yearLabel2;
    // End of variables declaration//GEN-END:variables
    private javax.swing.DefaultListModel<String> listModel = new DefaultListModel();
}
